// doris-ui/src/views/query/QueryProfile.vue
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/**
 * query Page
 */
<template>
  <div>
    <!-- 面包屑导航 -->
    <el-breadcrumb separator-class="el-icon-arrow-right">
      <el-breadcrumb-item :to="{ path: '/home/home' }">Home</el-breadcrumb-item>
      <el-breadcrumb-item :to="{ path: '/query/Query' }">Query</el-breadcrumb-item>
      <el-breadcrumb-item >Query Profile</el-breadcrumb-item>
    </el-breadcrumb>
    <el-form :inline="true" :model="formInline" class="user-search">
   </el-form>
   <div class="div1background">
        <div class="div2background">
            <pre>
              <div v-html="datamsg"></div>
            </pre>
        </div>
   </div>
  </div>
</template>

<script>
import { queryProfileList} from '../../api/doris'
import Pagination from '../../components/Pagination'
export default {
  data() {
    return {
      nshow: true, //switch开启
      datamsg:"",
      fshow: false, //switch关闭
      loading: false, //是显示加载
      editFormVisible: false, //控制编辑页面显示与隐藏
      title: '添加',
      editForm: {
        deptId: '',
        deptName: '',
        deptNo: '',
        token: localStorage.getItem('logintoken')
      },
      formInline: {
        page: 1,
        limit: 10,
        varLable: '',
        varName: '',
        token: localStorage.getItem('logintoken')
      },
      userparm: [], //搜索权限
      listData: [], //用户数据
      // 分页参数
      pageparm: {
        currentPage: 1,
        pageSize: 10,
        total: 10
      }
    }
  },
  // 注册组件
  components: {
    Pagination
  },
  /**
   * 数据发生改变
   */

  /**
   * 创建完毕
   */
  created() {
    this.getdata(this.formInline)
    self = this
  },
  /**
   * 里面的方法只有被调用才会执行
   */
  methods: {
    // 获取Frontend列表
    getdata(parameter) {
      this.loading = true
      queryProfileList(self.$route.params.id)
        .then(res => {
          this.loading = false
          if (res.success == false) {
  this.$message({
              type: 'info',
              message: res.msg
            })
          } else {
            console.log(res.data)
            this.datamsg = res.data         
          }
        })
        .catch(err => {
          this.loading = false
          this.$message.error('Authentication failed, Please login again')
          this.$router.push({ path: '/' })

        })
    },
    // 分页插件事件
    callFather(parm) {
      this.formInline.page = parm.currentPage
      this.formInline.limit = parm.pageSize
      this.getdata(this.formInline)
    },
    // 搜索事件
 
    // 关闭编辑、增加弹出框
    closeDialog() {
      this.editFormVisible = false
    }
  }
}
</script>

<style scoped>
.user-search {
  margin-top: 20px;
}
.userRole {
  width: 100%;
}
</style>

// ui/src/pages/query-profile/index.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
 
import React, {useState, useEffect, useRef} from 'react';
import {Typography, Button, Row, Col} from 'antd';
const {Text, Title, Paragraph} = Typography;
import {queryProfile} from 'Src/api/api';
import Table from 'Src/components/table';
import {useHistory} from 'react-router-dom';
export default function QueryProfile(params: any) {
    // const [parentUrl, setParentUrl] = useState('');
    const container = useRef();
    const [allTableData, setAllTableData] = useState({});
    const [profile, setProfile] = useState();
    const history = useHistory();
    const doQueryProfile = function(){
        const param = {
            path:location.pathname.slice(14),
        };
        queryProfile(param).then(res=>{
            if (res && res.msg === 'success') {
                if(!res.data.column_names){
                    setProfile(res.data);
                    container.current.innerHTML=res.data;
                }else{
                    setProfile('');
                    setAllTableData(res.data);
                }
            } else {
                setAllTableData({
                    column_names:[],
                    rows:[],
                });
            }
        })
            .catch(err=>{
                setAllTableData({
                    column_names:[],
                    rows:[],
                });
            });
    };
    useEffect(() => {
        doQueryProfile();
    }, [location.pathname]);
    function goPrev(){
        if (location.pathname === '/QueryProfile/') {return;}
        history.push('/QueryProfile/');
    }
    return(
        <Typography style={{padding:'30px'}}>
            <Title >Finished Queries</Title>

            <Row style={{paddingBottom:'15px'}}>
                <Col span={12} ><Text type="strong">This table lists the latest 100 queries</Text></Col>
                <Col span={12} style={{textAlign:'right'}}>
                    {profile?<Button  type="primary" onClick={goPrev}>back</Button>:''}
                </Col>
            </Row>
            {
                profile
                    ?<div ref={container} style={{background: '#f9f9f9',padding: '20px'}}>
                        {/* {profile} */}
                    </div>
                    :<Table
                        isSort={true}
                        isFilter={true}
                        isInner={true}
                        allTableData={allTableData}
                    />
            }

        </Typography>
    );
}
