// ui/src/pages/home/index.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
 
import React, {useState, useEffect} from 'react';
import {Typography, Divider, BackTop, Spin} from 'antd';
const {Title, Paragraph, Text} = Typography;
import {getHardwareInfo} from 'Utils/api';

export default function Home(params: any) {
    const [hardwareData , setHardwareData] = useState({});
    const getConfigData = function(){
        getHardwareInfo().then(res=>{
            if (res && res.msg === 'success') {
                setHardwareData(res.data);
            }
        })
            .catch(err=>{
                setHardwareData({
                    VersionInfo:{},
                    HarewareInfo:{},
                });
            });
    };
    function getItems(data, flag){
        let arr = [];
        for (const i in data) {
            if (flag) {
                arr.push(
                    <p key={i} dangerouslySetInnerHTML={createMarkup(i,data[i])} ></p>
                )
            } else {
                arr.push(
                    <p key={i}>{i + ' : ' + data[i]}</p>
                )
            }
        }
        return arr;
    }
    function createMarkup(key,data) {
        return {__html:key + ' : ' + String(data)};
    }
    useEffect(() => {
        getConfigData();
    }, []);
    return(
        <Typography style={{padding:'30px'}}>
            <Title>Version</Title>
            <Paragraph style={{background: '#f9f9f9',padding: '20px'}}>
                {...getItems(hardwareData.VersionInfo, false)}
            </Paragraph>
            <Divider/>
            <Title>Hardware Info</Title>
            <Paragraph style={{background: '#f9f9f9',padding: '20px'}}>
                {...getItems(hardwareData.HarewareInfo, true)}
            </Paragraph>
            <BackTop></BackTop>
            {hardwareData.HarewareInfo?'':<Spin style={{'position':'relative','top':'50%','left':'50%'}}/>}
        </Typography>
    );
}

// docs/.vuepress/theme/components/Home.vue
<!-- 
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<template>
  <div>
    <ParentLayout></ParentLayout>
    <footer>
      <CustomFooter />
    </footer>
  </div>
</template>
<script>
import ParentLayout from "@parent-theme/components/Home.vue";
import CustomFooter from "@theme/components/Footer.vue";

export default {
  components: {
    ParentLayout,
    CustomFooter
  }
};
</script>
