// doris-ui/src/views/login.vue
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

<template>
  <div class="login">
    <el-form label-position="left" :model="loginForm" :rules="rules" ref="loginForm" label-width="0px" class="demo-loginForm login-container">
      <h3 class="title">Apache Doris</h3>
      <el-form-item prop="username">
        <el-input type="text" v-model="loginForm.username" auto-complete="off" placeholder="username"></el-input>
      </el-form-item>
      <el-form-item prop="password">
        <el-input type="password" v-model="loginForm.password" auto-complete="off" placeholder="password"></el-input>
      </el-form-item>
      <el-form-item style="width:100%;">
        <el-button type="primary" style="width:100%;" @click="submitForm('loginForm')" :loading="logining">Login</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>
<script type="text/ecmascript-6">
import axios from 'axios';
import { setCookie, getCookie, delCookie } from '../utils/util'
import md5 from 'js-md5'
import Cookies from 'js-cookie'

export default {
  name: 'login',
  data() {
    return {
      logining: false,
      rememberpwd: false,
      loginForm: {
        username: '',
        password: ''
      },
      rules: {
        username: [{ required: true, message: 'please enter username', trigger: 'blur' }]
      }
    }
  },
  created() {
    self=this
  },
  methods: {
    getuserpwd() {
      if (getCookie('user') != '' && getCookie('pwd') != '') {
        this.loginForm.username = getCookie('user')
        this.loginForm.password = getCookie('pwd')
        this.rememberpwd = true
      }
    },
    submitForm(formName) {
      axios.post(this.baseurl+'rest/v1/login', {
        username: this.loginForm.username,
        password: this.loginForm.password
        })
        .then(function (response) {
        if(response.data.code === 200){
          Cookies.set("userName",self.loginForm.username)
          self.$router.push({ path: '/home/home' })
        } else if(response.data.code === 401){
          self.$router.push({ path: '/login' });
        }
        console.log(response);
        })
    },
  }
}
</script>

<style scoped>
.login {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  background-image: url("../assets/img/login-background.png");
  background-size: cover;
}
.login-container {
  border-radius: 10px;
  margin: 0px auto;
  width: 350px;
  padding: 30px 35px 15px 35px;
  background: #fff;
  border: 1px solid #eaeaea;
  text-align: left;
  box-shadow: 0 0 20px 2px rgba(0, 0, 0, 0.1);
}
.title {
  margin: 0px auto 40px auto;
  text-align: center;
  color: #505458;
}
.remember {
  margin: 0px 0px 35px 0px;
}
.code-box {
  text-align: right;
}
.codeimg {
  height: 40px;
}
</style>

// ui/src/pages/login/index.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
 
import React,{useState} from 'react';
import {Form, Input, Button, Checkbox} from 'antd';
import request from 'Utils/request';
import {useHistory} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import styles from './index.less';
import './cover.less';
function Login(){
    let { t } = useTranslation();
    const [username, setUsername] = useState();
    const history = useHistory();
    const layout = {
        labelCol: {span: 8},
        wrapperCol: {span: 24},
        layout='vertical',
    };
    const tailLayout = {
        wrapperCol: {span: 24},
    };

    interface Result<T> {
        content: T;
        status: string;
        partialResults: boolean;
        msg: string;
        code: number;
    }
    function login<T>(data: any): Promise<Result<T>> {
        return request('/rest/v1/login', {
            method: 'POST',
            headers:{Authorization: data.password?`Basic ${btoa(data.username+':'+data.password)}`:`Basic ${btoa(data.username+':')}`},
        });
    }
    const onFinish = values => {
        login(values).then(res=>{
            if(res.code===200){
                history.push('/home');
                localStorage.setItem('username', username)
            }
        });
    };

    const onFinishFailed = errorInfo => {
        console.log('Failed:', errorInfo);
    };
    // 878CB1
    // 31395B
    return (
        <div className={[styles['background'],'login'].join(' ')}>
            <div className={styles['logo']}></div>
            <Form
                {...layout}
                name="basic"
                initialValues={{remember: true}}
                onFinish={onFinish}
                layout='vertical'
                requiredMark={false}
                onFinishFailed={onFinishFailed}
                className={styles['login-form']}
            >
                <Form.Item
                    label={t('username')}
                    name="username"
                    rules={[{required: true, message: 'Please input your username!'}]}
                >
                    <Input value={username} onChange={(e)=>{setUsername(e.target.value)}} />
                </Form.Item>

                <Form.Item
                    label={t('password')}
                    name="password"
                    rules={[{required: false, message: 'Please input your password!'}]}
                >
                    <Input.Password/>
                </Form.Item>

                <Form.Item {...tailLayout}>
                    <Button type="primary" shape="round" style={{'width':'100%'}} htmlType="submit">
                        {t('login')}
                    </Button>
                </Form.Item>
            </Form>
        </div>
    );
}

export default Login;
