// manager/doris-manager/src/routes/query/index.tsx
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/* eslint-disable prettier/prettier */
import React, { useState, useEffect } from 'react';
import { Table, Card, Space, Input } from 'antd';
import { useTranslation } from 'react-i18next';
import { getQueryInfo } from './query.api';
import { ColumnsType } from 'antd/es/table';
import { FILTERS } from './query.data';
import { useHistory } from 'react-router-dom';
import { ClippedText } from '@src/components/clipped-text/clipped-text';
const { Search } = Input;

interface ICol {
    [propName: string]: any;
}

function Query() {
    const { t } = useTranslation();
    const history = useHistory();
    const [tableData, setTableData] = useState<ICol[]>([]);
    const [tableColumn, setTableColumn] = useState<ColumnsType<ICol>>([]);

    function queryDetails(record: any) {
        console.log(record)
        history.push(`/details/${record[0]}`)
    }
    useEffect(() => {
        getQueryInfo().then(res => {
            const { column_names, rows } = res.data;
            handleResult(column_names, rows);
        });
    }, []);
    const onSearch = (value: string) => {
        let newValue = encodeURI(value)
        getQueryInfo({
            search: newValue,
        }).then(res => {
            const { column_names, rows } = res.data;
            handleResult(column_names, rows);
        });
    };

    const handleResult = (column_names: string[], rows: [][]) => {
        const columns = column_names.map((item: string, index: number) => {
            if (item === 'Query ID') {
                return {
                    title: item,
                    dataIndex: `${index}`,
                    key: item,
                    columnWidth: 10,
                    render: (text: any, record: any, index: any) => (
                        <ClippedText text={text}>
                            <Space size="middle">
                                <a onClick={() => queryDetails(record)}>{text}</a>
                            </Space>
                        </ClippedText>
                        
                    ),
                };
            }
            if (item === '状态') {
                return {
                    title: item,
                    dataIndex: `${index}`,
                    key: item,
                    columnWidth: 10,
                    filters: FILTERS,
                    onFilter: (value: any, record: any) => record[index].indexOf(value) === 0,
                };
            }
            if (item === 'FE节点') {
                return {
                    title: item,
                    dataIndex: index,
                    key: item,
                    width: 150,
                    ellipsis: true,
                };
            }
            if (item === '开始时间') {
                return {
                    title: item,
                    dataIndex: index,
                    key: item,
                    width: 150,
                    ellipsis: true,
                };
            }
            if (item === '结束时间') {
                return {
                    title: item,
                    dataIndex: index,
                    key: item,
                    width: 150,
                    ellipsis: true,
                };
            }
            return {
                title: item,
                dataIndex: index,
                key: item,
                columnWidth: 10,
                ellipsis: true,
            };
        });
        setTableColumn(columns);
        setTableData(rows.map((item: string[]) => ({ ...item })));
    };

    return (
        <>
            <Card
                style={{ width: '100%' }}
                title={t`queryProfileFirst`}
                extra={<Search placeholder="搜索" onSearch={onSearch} allowClear/>}
            >
                <Table<ICol>
                    columns={tableColumn}
                    dataSource={tableData}
                    bordered
                    scroll={{ x: 1300 }}
                    size="middle"
                    pagination={{
                        pageSizeOptions: ['10', '20', '50'],
                    }}
                    locale={{emptyText: t`noDate` }}
                ></Table>
            </Card>
        </>
    );
}

export default Query;

// doris-ui/src/views/query/Query.vue
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/**
 * query Page
 */
<template>
  <div>
    <!-- 面包屑导航 -->
    <el-breadcrumb separator-class="el-icon-arrow-right">
      <el-breadcrumb-item :to="{ path: '/home/home' }">Home</el-breadcrumb-item>
      <el-breadcrumb-item :to="{ path: '/Query' }">Query</el-breadcrumb-item>
    </el-breadcrumb>
   <el-form :inline="true" :model="formInline" class="user-search">
   </el-form>
    <!--列表-->
    <el-table size="small" :data="listData" highlight-current-row v-loading="loading" border element-loading-text="loading..." style="width: 100%;" @row-click="query_info">
      <el-table-column align="center" type="selection" width="60">
      </el-table-column>
      <el-table-column sortable prop="User" label="User">
      </el-table-column>
      <el-table-column sortable prop="Query Type" label="Query Type" >
      </el-table-column>
      <el-table-column sortable prop="Total" label="Total" >
      </el-table-column>
       <el-table-column sortable prop="Default Db" label="Default Db" >
      </el-table-column>
      <el-table-column sortable prop="Sql Statement" label="Sql Statement" >
      </el-table-column>
      <el-table-column sortable prop="Start Time" label="Start Time" >
      </el-table-column>
      <el-table-column sortable prop="Query State" label="Query State" >
      </el-table-column>
      <el-table-column sortable prop="End Time" label="End Time" >
      </el-table-column>
      <el-table-column sortable prop="QueryId" label="QueryId" >
      </el-table-column>      
    </el-table>
    <!-- 分页组件 -->
    <Pagination v-bind:child-msg="pageparm" @callFather="callFather"></Pagination>
  </div>
</template>

<script>
import { queryList} from '../../api/doris'
import Pagination from '../../components/Pagination'
export default {
  data() {
    return {
      nshow: true, //switch开启
      fshow: false, //switch关闭
      loading: false, //是显示加载
      editFormVisible: false, //控制编辑页面显示与隐藏
      title: '添加',
      editForm: {
        deptId: '',
        deptName: '',
        deptNo: '',
        token: localStorage.getItem('logintoken')
      },
      formInline: {
        page: 1,
        limit: 10,
        varLable: '',
        varName: '',
        token: localStorage.getItem('logintoken')
      },
      userparm: [], //搜索权限
      listData: [], //用户数据
      // 分页参数
      pageparm: {
        currentPage: 1,
        pageSize: 10,
        total: 10
      }
    }
  },
  // 注册组件
  components: {
    Pagination
  },
  /**
   * 数据发生改变
   */

  /**
   * 创建完毕
   */
  created() {
    this.getdata(this.formInline)
    self = this
  },

  /**
   * 里面的方法只有被调用才会执行
   */
  methods: {
  query_info(row, event, column){
    console.log("QueryId = "+ row.QueryId)
    self.$router.push({ 
         path: '/query/QueryProfile/'+row.QueryId.replace(/%/g, '%25') 
    })
  },
    // 获取Frontend列表
    getdata(parameter) {
      this.loading = true
      queryList(parameter)
        .then(res => {
          this.loading = false
          if (res.success == false) {
            this.$message({
              type: 'info',
              message: res.msg
            })
          } else {
            this.listData = res.data
            // 分页赋值
            this.pageparm.currentPage = this.formInline.page
            this.pageparm.pageSize = this.formInline.limit
            this.pageparm.total = res.count
          }
        })
        .catch(err => {
          this.loading = false
          this.$message.error('菜单加载失败，请稍后再试！')
        })
    },
    // 分页插件事件
    callFather(parm) {
      this.formInline.page = parm.currentPage
      this.formInline.limit = parm.pageSize
      this.getdata(this.formInline)
    },
    // 搜索事件
 
    // 关闭编辑、增加弹出框
    closeDialog() {
      this.editFormVisible = false
    }
  }
}
</script>

<style scoped>
.user-search {
  margin-top: 20px;
}
.userRole {
  width: 100%;
}
</style>
